name: terraform apply

on:
  push:
    branches:
      - main

env:
  terraform_version: "1.5.7"
  working_directory: "./"
  TF_VAR_bitwarden_email: ${{ secrets.TF_VAR_BITWARDEN_EMAIL }}
  TF_VAR_bitwarden_master_password: ${{ secrets.TF_VAR_BITWARDEN_MASTER_PASSWORD }}
  TF_VAR_bitwarden_client_id: ${{ secrets.TF_VAR_BITWARDEN_CLIENT_ID }}
  TF_VAR_bitwarden_client_secret: ${{ secrets.TF_VAR_BITWARDEN_CLIENT_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: bitwarden_install
        shell: bash
        run: |
          echo "Install Bitwarden CLI"
          curl -Lo bw.zip https://github.com/bitwarden/clients/releases/download/cli-v2024.1.0/bw-linux-2024.1.0.zip
          unzip bw.zip -d .
          sudo install bw /usr/local/bin/
          rm -f bw bw.zip

      - name: init
        shell: bash
        working-directory: ${{ env.working_directory }}
        run: terraform init

      - name: plan
        shell: bash
        working-directory: ${{ env.working_directory }}
        run: terraform plan

      - name: apply
        shell: bash
        working-directory: ${{ env.working_directory }}
        run: terraform apply -auto-approve -input=false -no-color 2>&1
