name: terraform apply

on:
  push:
    branches:
      - main

env:
  terraform_version: "1.5.7"
  path: "./"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: terraform init
        id: init
        shell: bash
        working-directory: ${{ env.path }}
        run: terraform init
        env:
          TF_VAR_bitwarden_email: ${{ secrets.TF_VAR_BITWARDEN_EMAIL }}
          TF_VAR_bitwarden_master_password: ${{ secrets.TF_VAR_BITWARDEN_MASTER_PASSWORD }}
          TF_VAR_bitwarden_client_id: ${{ secrets.TF_VAR_BITWARDEN_CLIENT_ID }}
          TF_VAR_bitwarden_client_secret: ${{ secrets.TF_VAR_BITWARDEN_CLIENT_SECRET }}

      - name: terraform apply
        id: apply
        shell: bash
        working-directory: ${{ env.path }}
        run: terraform apply -auto-approve -input=false -no-color 2>&1
